### ISSUE TITLE
Abstract Text problem

### ISSUE THREAD

**Issue by parisni** [skoval/RISmed#1]
Hello,

I encountered an error using your package : The abstractText seems to retrieve just the "Objective" section from Medline whereas, I expected a list of : 
INTRODUCTION, OBJECTIVE , METHODS, RESULTS, CONCLUSIONS (as described http://www.nlm.nih.gov/bsd/licensee/elements_descriptions.html)

Thanks adavance and sorry if I didn't use correctly your package.
Anyway, an interesting package and great S4 programming

**Comment by skoval** [comment]
Hi,

Thanks for pointing out the issue with the structured abstracts. I think this has now been addressed. If you could install the current version of the package from this repo and let me know if this has fixed the issue you encountered that would be great. I did some test cases myself but always good to have additional checks.
