### ISSUE TITLE
EUtilsGet does not fetch some of the available abstracts

### ISSUE THREAD

**Issue by gusmmm** [skoval/RISmed#13]
This record on pubmed has an abstract:
https://www.ncbi.nlm.nih.gov/pubmed/29397598

But when using a EUtilSummary followed by a EUtilsGet, the functions don't succeed in fetching the abstract:
topic <- '("shock, septic"[MeSH Terms] OR ("shock"[All Fields] AND "septic"[All Fields]) OR "septic shock"[All Fields] OR ("septic"[All Fields] AND "shock"[All Fields])) AND ("2013/04/21"[PDat] : "2018/04/19"[PDat] AND "humans"[MeSH Terms])'
query <- EUtilsSummary(topic,retmax= 100,db = "pubmed",type = "esearch")
records <- EUtilsGet(query)

The record with PMID 29397598 has failed to fetch the abstract even though it is available in the pubmed site. There are other similar examples in this query.

Can you help? Thanks!

**Comment by skoval** [comment]
I am able to see the Abstract for  29397598 with the current version (2.2.1). There is a foreign language as well (maybe this was the case with some of the others) which might have resulted in an NA due to an encoding issue in an earlier version.
