### ISSUE TITLE
Author list not always correct

### ISSUE THREAD

**Issue by Toxgondii** [skoval/RISmed#14]
Hello,

**I have a question about the Rismed R package.
The list I get after an author search is not fully correct.
Example:
When I search pubmed for “(Kuczyk MA) AND (2018)”
 
I get:**
 
1: Ückert S, Becker AJ, Bannowsky A, Stief CG, Kuczyk MA. Is β-endorphin
significant in the control of the male sexual response? Andrologia. 2018 May
20:e13049. doi: 10.1111/and.13049. [Epub ahead of print] PubMed PMID: 29781087.
 
 
2: Shahin P, Rahardjo HE, Bannowsky A, Tsikas D, Sohn M, Kuczyk MA, Ückert S.
Endopeptidase inhibition attenuates the contraction induced by big endothelin-1
of isolated human penile erectile tissue. Andrologia. 2018 Mar 25:e13008. doi:
10.1111/and.13008. [Epub ahead of print] PubMed PMID: 29574984.
 
 
3: Hupe MC, Vahlensieck W, Ozimek T, Struck JP, Hennig MJP, Tezval H, von Klot
CA, Merseburger AS, Kuczyk MA, Kramer MW. Diarrhea and flatulence are major bowel
disorders after radical cystectomy: Results from a cross-sectional study in
bladder cancer patients. Urol Oncol. 2018 May;36(5):237.e1-237.e8. doi:
10.1016/j.urolonc.2017.12.014. Epub 2018 Feb 1. PubMed PMID: 29395950.
 
 
4: Henkenberens C, Derlin T, Bengel FM, Ross TL, Wester HJ, Hueper K, Kuczyk MA, 
Christiansen H, von Klot CA. Patterns of relapse as determined by (68)Ga-PSMA
ligand PET/CT after radical prostatectomy : Importance for tailoring and
individualizing treatment. Strahlenther Onkol. 2018 Apr;194(4):303-310. doi:
10.1007/s00066-017-1231-9. Epub 2017 Nov 13. PubMed PMID: 29134231.
 
 
5: Ückert S, la Croce G, Bettiga A, Albrecht K, Buono R, Benigni F, Kuczyk MA,
Hedlund P. Expression and distribution of key proteins of the endocannabinoid
system in the human seminal vesicles. Andrologia. 2018 Mar;50(2). doi:
10.1111/and.12875. Epub 2017 Aug 8. PubMed PMID: 28786134.

**However, if I do the same search with RISmed. And look for the first author, “Ueckert S” does not show up at all. Do you have an explanation for this, or a solution? 
I thought this might have something todo with the german umlaut 'ü' (ue). However other authors with the umlaut 'ü' show up just fine.
(please mind the first entry in the first and fifth list element ([[1]], [[5]]))**
 
```
library(RISmed)
library(zoo)
res <- EUtilsSummary("(kuczyk MA) AND (2018)",retmax=500)
medobj <- EUtilsGet(res)
Author(medobj)
```
 
[[1]]
   LastName    ForeName Initials order
1    Becker     Armin J       AJ     1
2 Bannowsky     Andreas        A     2
3     Stief Christian G       CG     3
4    Kuczyk    Markus A       MA     4
 
[[2]]
   LastName ForeName Initials order
1    Shahin        P        P     1
2  Rahardjo      H E       HE     2
3 Bannowsky        A        A     3
4    Tsikas        D        D     4
5      Sohn        M        M     5
6    Kuczyk      M A       MA     6
 
[[3]]
      LastName    ForeName Initials order
1         Hupe     Marie C       MC     1
2  Vahlensieck    Winfried        W     2
3       Ozimek      Tomasz        T     3
4       Struck    Julian P       JP     4
5       Hennig  Martin J P      MJP     5
6       Tezval     Hossein        H     6
7     von Klot Christoph A       CA     7
8  Merseburger      Axel S       AS     8
9       Kuczyk    Markus A       MA     9
10      Kramer     Mario W       MW    10
 
[[4]]
      LastName    ForeName Initials order
1 Henkenberens   Christoph        C     1
2       Derlin    Thorsten        T     2
3       Bengel     Frank M       FM     3
4         Ross    Tobias L       TL     4
5       Wester Hans-Jürgen       HJ     5
6       Hueper       Katja        K     6
7       Kuczyk    Markus A       MA     7
8 Christiansen        Hans        H     8
9     von Klot Christoph A       CA     9
 
[[5]]
  LastName ForeName Initials order
1 la Croce        G        G     1
2  Bettiga        A        A     2
3 Albrecht        K        K     3
4    Buono        R        R     4
5  Benigni        F        F     5
6   Kuczyk      M A       MA     6
7  Hedlund        P        P     7
 
 
**Kind Regards
Toxgondii**

**Comment by skoval** [comment]
Yes, I think the earlier version was using an encoding that was setting strings with accents to NA. This should be corrected with the latest version (2.2.1).
