### ISSUE TITLE
Cited function fails because of too many requests to PubMed Central in a second

### ISSUE THREAD

**Issue by tzengji** [skoval/RISmed#15]
When using CIted function as the example in the manual, it gets: 
Error in readLines(the_url) : cannot open the connection
In addition: Warning message:
In readLines(the_url) :
  cannot open URL 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?retmode=xml&dbfrom=pubmed&id=11816901&cmd=neighbor': HTTP status was '429 Too Many Requests'.

The reason is that the E-utility servers set rate limiting to avoid overloading. 

To solve the problem, you can add
Sys.sleep(1) (or Sys.sleep(0.1))
as the first line within the function(id) of Cited function.

Tzeng-Ji Chen

**Comment by skoval** [comment]
I only get a 0 count for that example because there do not appear to be PMIDs listed under the 'citedin' type for the elink results.
