### ISSUE TITLE
Problems retrieving pmids using EUtilsSummary

### ISSUE THREAD

**Issue by ghlopez** [skoval/RISmed#16]
Hello, 

I noticed some problems with the number of pmids that re retrieved using EUtilsSummary. The internal number of pmids does not match the number of articles retrived in the query. 

> library(RISmed)
> PMQuery <- '("delirium"[TIAB] OR "Delirium"[Mesh]) AND ("1900/01/01"[EDAT] : "2019/06/01"[EDAT])'
> search_query <- EUtilsSummary(PMQuery, retmax=50000)
There were 30 warnings (use warnings() to see them)
> summary(search_query)
Query:
("delirium"[TIAB] OR "Delirium"[Mesh]) AND ("1900/01/01"[EDAT] : "2019/06/01"[EDAT]) 

Result count:  15527
> pubmed_data <- search_query@PMID
> length(pubmed_data)
[1] 15458

I have been rerunning the query several times and if I try to do so the system returns different number of pmids each time. 
(warnings can be removed running Sys.setlocale('LC_ALL','C'))

R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.15.1
RISmed_2.1.12

**Comment by skoval** [comment]
Do you see the same changes in the results when you submit the query multiple times on Pubmed?

**Comment by ghlopez** [comment]
Hi Steph thanks for following this up.

The search always returns the same number 15527 of papers is when I try to extract the papers when the problem arises and the number of pmids retrieved(search_query@PMID) changes. I have run the same query using rentrez library and that one seems to be working fine. Check below.

lpmids <- list()
lpmids.2 <- list()
PMQuery<- '("delirium"[TIAB] OR "Delirium"[Mesh]) AND ("1900/01/01"[EDAT] : "2019/06/01"[EDAT])'
for (i in 1:10){
  search_query <- EUtilsSummary(PMQuery, retmax=50000)
  summary(search_query)
  pubmed_data <- search_query@PMID
  lpmids[[i]] <- (pubmed_data)
  r_searchp <- entrez_search(db="pubmed", term= PMQuery, retmax=50000)
  lpmids2[[i]] <- r_searchp[["ids"]]
}


> length(lpmids[[1]])
[1] 15410
> length(lpmids[[2]])
[1] 15390
> length(lpmids[[3]])
[1] 15387
> length(lpmids[[4]])
[1] 15390
> length(lpmids[[5]])
[1] 15500
> length(lpmids[[6]])
[1] 15469
> length(lpmids2[[1]])
[1] 15527
> length(lpmids2[[2]])
[1] 15527
> length(lpmids2[[3]])
[1] 15527
> length(lpmids2[[4]])
[1] 15527

**Comment by ghlopez** [comment]
Hi Steph thanks for following this up.

The search always returns the same number 15527 of papers is when I try to extract the papers when the problem arises and the number of pmids retrieved(search_query@PMID) changes. I have run the same query using rentrez library and that one seems to be working fine. Check below.

lpmids <- list()
lpmids2 <- list()
PMQuery<- '("delirium"[TIAB] OR "Delirium"[Mesh]) AND ("1900/01/01"[EDAT] : "2019/06/01"[EDAT])'
for (i in 1:10){
search_query <- EUtilsSummary(PMQuery, retmax=50000)
summary(search_query)
pubmed_data <- search_query@PMID
lpmids[[i]] <- (pubmed_data)
r_searchp <- entrez_search(db="pubmed", term= PMQuery, retmax=50000)
lpmids2[[i]] <- r_searchp[["ids"]]
}

length(lpmids[[1]])
[1] 15410
length(lpmids[[2]])
[1] 15390
length(lpmids[[3]])
[1] 15387
length(lpmids[[4]])
[1] 15390
length(lpmids[[5]])
[1] 15500
length(lpmids[[6]])
[1] 15469
length(lpmids2[[1]])
[1] 15527
length(lpmids2[[2]])
[1] 15527
length(lpmids2[[3]])
[1] 15527
length(lpmids2[[4]])
[1] 15527
