### ISSUE TITLE
Error: invalid class “EUtilsSummary” object

### ISSUE THREAD

**Issue by lz01** [skoval/RISmed#17]
Hello,

I get the following error:

> Error in validObject(.Object) : 
>   invalid class “EUtilsSummary” object: invalid object for slot "PMID" in class "EUtilsSummary": got class "list", should be or extend class "character"

when I run EUtilsSummary with a retmax>1000 and the query returns 0 hits. The error doesn't happen if only one of these two conditions is true (either retmax<=1000 and 0 hits, or retmax>1000 and at least one hit).

For example, these two examples work fine:
```
res1 = EUtilsSummary("molecular biology and evolution[ta]", type = "esearch", db = "pubmed", datetype = 'pdat', mindate = 1970, maxdate = 1980, retmax = 1000)
res2 = EUtilsSummary("molecular biology and evolution[ta]", type = "esearch", db = "pubmed", datetype = 'pdat', mindate = 1980, maxdate = 1990, retmax = 1001) 
```

but this one doesn't:

```
res3 = EUtilsSummary("molecular biology and evolution[ta]", type = "esearch", db = "pubmed", datetype = 'pdat', mindate = 1970, maxdate = 1980, retmax = 1001)
```
In this case, res1 and res3 should be equivalent, and their number of hits is 0 (`QueryCount(res1)` is 0).

Thanks!

**Comment by lz01** [comment]
The error seems to come from the fact that in the case of `res3`, `EMPTYCHECK` does not get set to `TRUE`, because the `lines` variable in `EUtilsSummary.R` returns the <eSearchResult>...</eSearchResult> part as 3 elements instead of 1, and therefore the `grep` for `<eSearchResult><Count>0<\\/Count>` doesn't work.
Either concatenating the 3 elements into 1 or amending the `grep` to `^(?:<eSearchResult>)?<Count>0<\\/Count>` solves the issue.

**Comment by skoval** [comment]
Thank you for this suggestion. I've add this correction as part of version 2.2.2.
