### ISSUE TITLE
EUtilsGet is broken         

### ISSUE THREAD

**Issue by lmoffatt** [skoval/RISmed#23]
EUtilsGet is broken since june 28 2021, it was working fine on June 25 2021. 

My guess is that PubMed changed the format of their output so EUtilsGet stopped understanding it. 

The Medline object is created but it does not contain any records although it generates internet traffic as I could tell by monitoring it.

**Comment by jonnye2** [comment]
> EUtilsGet is broken since june 28 2021, it was working fine on June 25 2021.
> 
> My guess is that PubMed changed the format of their output so EUtilsGet stopped understanding it.
> 
> The Medline object is created but it does not contain any records although it generates internet traffic as I could tell by monitoring it.

I'm having the same issue. EUtilsGet returns no information in the Medline object.

**Comment by skoval** [comment]
I've just pushed an update to address this issue. It would be great if you both could do some testing on your own systems (install the latest version via remotes::install_github). If you encounter any issues, please provide a reproducible code snippet here along with some description of relevant system specs.

**Comment by lmoffatt** [comment]
I just did 
remotes::install_github("skoval/RISmed"), 
and problem solved!!

**Comment by jonnye2** [comment]
Working great now. Thanks!
