### ISSUE TITLE
EUtilsGet error. Error in data.frame… differing number of rows. 

### ISSUE THREAD

**Issue by jonnye2** [skoval/RISmed#24]
Installed the latest github version and getting an error when using EUtilsGet. 

Error in data.frame(CollectiveName = NA, LastName = as.character(z$LastName[[1]]),  : 
  arguments imply differing number of rows: 1, 0

`library(RISmed)
library(remotes)
remotes::install_github("skoval/RISmed")

test <- "GREEN KY[AUTH]"
summary <- EUtilsSummary(test, type='esearch', db='pubmed', reldate = 720)
records <- EUtilsGet(summary, type="efetch", db = 'pubmed')`

**Comment by skoval** [comment]
Thanks for this example. It looks like there are some instances where a "CollectiveName" is assigned to LastName in the Author XML. Had made the assumption that it would always be under the "CollectiveName" field. The latest commit provides some solution which I hope will cover the majority of cases now.
