### ISSUE TITLE
Error in EUtilsGet

### ISSUE THREAD

**Issue by Matthew-Ryan1995** [skoval/RISmed#25]
Hey,

I have been using this package to great effect, but I have come across a weird error in my latest scrape of PubMed.

If found that:

test1 <- EUtilsSummary("33658733[PMID]")
EUtilsGet(test1)

returns:

Error in x$PubmedData$History[[i]] : subscript out of bounds

After digging around I believe the error occurs due to line 96 of `ParseMedline.R`.  The line of code is:

pubmed_states <- sapply(x$PubmedData$History, function(z) attr(z, "PubStatus"))

and sadly some states are returning double ups.  I was able to fix this in my code by using

pubmed_states <- sapply(x$PubmedData$History, function(z) attr(z, "PubStatus"))
pubmed_states <- unique(pubmed_states)

However I don't know if I am accidentally breaking anything in doing this.

It is a really odd error and I thought I should bring it to your attention.

Kind regards,
Matt

**Comment by skoval** [comment]
You are completely right. The duplicates in PubStatus entries was causing an error. Since they do appear to be duplicates, I think we can safely take the first instance. Let me know if the latest commit addresses the issue.

**Comment by Matthew-Ryan1995** [comment]
Seems to work well. Thank you!
