### ISSUE TITLE
accessing DOI

### ISSUE THREAD

**Issue by jcolomb** [skoval/RISmed#5]
is there a way to get dois automatically or convert the PubmedID into a doi (https://www.ncbi.nlm.nih.gov/pmc/tools/id-converter-api/). 
Sorry I do not have the skills to do it myself (yet?).

It would allow to create link to the full text very easily.

**Comment by Rhinocerotic** [comment]
Try this:

library(rentrez)
pmid <- "27718768"
pmid_summary <- entrez_summary(db="pubmed", id=pmid)
article_ids <- extract_from_esummary(pmid_summary, "articleids")
article_ids
article_ids$value[2]

Note that the order article_ids are displayed varies by record; for example
in this record the doi value was located on the second row
(article_ids$value[2]). Printing article_ids will display all ids
associated with the pmid, and doi is easy to locate among the others
(usually pmid).

**Comment by skoval** [comment]
With the current version (2.2.1), there is a DOI method so you can extract any DOI listed in the Medline object with

```
# x Medline object
DOI(x)
```
