### ISSUE TITLE
warnings when using EUtilsGet

### ISSUE THREAD

**Issue by MichelMoser** [skoval/RISmed#6]
Dear RISmed developer, 

I run into a few warnings when trying to get the queried publications. 
Further, i get 23 fewer publications than i see by the querycount.
Is this an issue of malformed publications on pubmed which fail to get downloaded?
Is there a way to get the ID or any Information about the failing publications? 

```
QueryCount(ngs_search)
```

[1] 18443

```
> ngs_records <- EUtilsGet(ngs_search)
```

Warning messages:
1: In index + 1:5 :
  longer object length is not a multiple of shorter object length
2: In index + 1:5 :
  longer object length is not a multiple of shorter object length
3: In index + 1:5 :
  longer object length is not a multiple of shorter object length
4: In index + 1:5 :
  longer object length is not a multiple of shorter object length
5: In index + 1:5 :
  longer object length is not a multiple of shorter object length
6: In index + 1:5 :
  longer object length is not a multiple of shorter object length
7: In Medline(Result, query) : NAs introduced by coercion
8: In Medline(Result, query) : NAs introduced by coercion

```
ngs_records
```

PubMed query:  resilience[All Fields] OR resiliency[All Fields] OR resilient[All Fields] AND 1900[EDAT] : 2016[EDAT] 

Records:  18420 

 It would be great if you could comment on this issue. 
Thank you very much, 
Michel

**Comment by lukeholman** [comment]
Hi there, just adding a note that I get the same exact error when calling EUtilsGet. Thanks for a great package!

**Comment by skoval** [comment]
There are no longer warnings for this query. However, I do see a small discrepancy in the count when the query is entered in the pubmed text box. I believe this is due to pubmed expanding the search query. You can see this in the Advanced feature (https://pubmed.ncbi.nlm.nih.gov/advanced/). For example, it includes terms like 'resiliencies', which doesn't happen with the EUtils API.
