### ISSUE TITLE
EUtilsSumary fails - probably http/https issue

### ISSUE THREAD

**Issue by yadbor** [skoval/RISmed#7]
Hi Stephanie,

RISmed was working well for me, but failed this morning with the error message
"Error in file(con, "r") : cannot open the connection"

Checking NCBI's site this is probably due to their change to use https for all requests now. See https://www.ncbi.nlm.nih.gov/home/develop/https-guidance.shtml for details.

The fix would appear to be to change RISmed/R/EUtils.R line 7 from
url <- 	"http://eutils.ncbi.nlm.nih.gov/entrez/eutils/type.fcgi?db=DB&"
to 
url <- 	"https://eutils.ncbi.nlm.nih.gov/entrez/eutils/type.fcgi?db=DB&"

that appears to be the only place you assemble to actual request URL.

I am completely new to GitHub, so apologies in advance if I am going about this the wrong way.

**Comment by jimrothstein** [comment]
I have same problem:

> Error in file(con, "r") : cannot open the connection

`> traceback()`
3: file(con, "r")
2: readLines(url, warn = FALSE, encoding = encoding)
1: EUtilsSummary("PTEN", db = "pubmed")
